# Generated by Django 3.1.7 on 2021-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('email', models.EmailField(max_length=150, verbose_name='Почта автора')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст записи')),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('time_of_update', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=150)),
            ],
            options={
                'verbose_name': 'Гостевая книга',
                'verbose_name_plural': 'Гостевая книги',
                'db_table': 'Guestbook',
            },
        ),
    ]
